[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "ib-insync>=0.9.86",
    "nest-asyncio>=1.6.0",
    "numpy>=2.3.0",
    "pandas>=2.3.0",
    "scipy>=1.15.3",
]
